"""Ajout champ is_comptable

Revision ID: aaaa3ec0ed48
Revises: c3d7303398bc
Create Date: 2026-05-18 12:37:18.726862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaaa3ec0ed48'
down_revision = 'c3d7303398bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_comptable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membres', schema=None) as batch_op:
        batch_op.drop_column('is_comptable')

    # ### end Alembic commands ###
