"""Ajout service, emploi et date_adhesion string

Revision ID: b7dbc79eb504
Revises: aaaa3ec0ed48
Create Date: 2026-05-19 15:24:45.425395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dbc79eb504'
down_revision = 'aaaa3ec0ed48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emploi', sa.String(length=100), nullable=True))
        batch_op.alter_column('date_adhesion',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membres', schema=None) as batch_op:
        batch_op.alter_column('date_adhesion',
               existing_type=sa.String(length=20),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('emploi')
        batch_op.drop_column('service')

    # ### end Alembic commands ###
