"""Initialisation complète corrigée

Revision ID: c3d7303398bc
Revises: 
Create Date: 2026-05-14 13:01:09.701525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d7303398bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donateur_nom', sa.String(length=100), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evenements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('budget_prevu', sa.Float(), nullable=True),
    sa.Column('depenses_reelles', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('ville', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('date_adhesion', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('fonction', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projets',
    sa.Column('idprojet', sa.Integer(), nullable=False),
    sa.Column('titreprojet', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datedebut', sa.DateTime(), nullable=True),
    sa.Column('datefiprojet', sa.DateTime(), nullable=True),
    sa.Column('coutexecution', sa.Float(), nullable=True),
    sa.Column('nomdonateur', sa.String(length=200), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('idprojet')
    )
    op.create_table('aides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('type_aide', sa.String(length=50), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_attribution', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('valide_par_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('type_cotisation', sa.String(length=50), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('periode', sa.String(length=20), nullable=True),
    sa.Column('date_paiement', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotisations')
    op.drop_table('aides')
    op.drop_table('projets')
    op.drop_table('membres')
    op.drop_table('evenements')
    op.drop_table('dons')
    # ### end Alembic commands ###
